# Generated by Django 6.1 on 2026-09-04 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('round_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('WAITING_FOR_PAYMENT', 'Waiting for Payment'), ('READY_FOR_PAYOUT', 'Ready for Payout'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=30)),
                ('expected_payout_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='groups.cycle')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient_rounds', to='groups.groupmembership')),
            ],
            options={
                'ordering': ['cycle', 'round_number'],
                'indexes': [models.Index(fields=['cycle', 'status'], name='round_cycle_status_idx'), models.Index(fields=['recipient'], name='round_recipient_idx')],
                'constraints': [models.UniqueConstraint(fields=('cycle', 'round_number'), name='unique_round_number_per_cycle')],
            },
        ),
    ]
