# Generated by Django 6.1 on 2026-09-04 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived')], default='PENDING', max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='groups.groupmembership')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='groups.round')),
            ],
            options={
                'ordering': ['due_date', 'id'],
                'indexes': [models.Index(fields=['round', 'status'], name='contrib_round_status_idx'), models.Index(fields=['member', 'status'], name='contrib_member_status_idx'), models.Index(fields=['status', 'due_date'], name='contrib_status_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('round', 'member'), name='unique_contribution_per_round_member')],
            },
        ),
    ]
