# Generated by Django 6.0.8 on 2026-10-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_groupmembership_membership_group_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('LEAVE_REQUESTED', 'Leave Requested'), ('LEFT', 'Left'), ('REMOVED', 'Removed'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20),
        ),
    ]
