# Generated by Django 6.0.8 on 2026-10-05 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_groupmembership_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_memberships', to='groups.cycle')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_memberships', to='groups.groupmembership')),
            ],
            options={
                'ordering': ['cycle', 'position'],
                'constraints': [models.UniqueConstraint(fields=('cycle', 'membership'), name='unique_cycle_membership'), models.UniqueConstraint(fields=('cycle', 'position'), name='unique_cycle_position')],
            },
        ),
    ]
