# Generated by Django 6.0.8 on 2026-10-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_cyclemembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('LOCKED', 'Locked')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='cycle',
            name='swap_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
