# Generated by Django 6.0.8 on 2026-10-07 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_cycle_order_status_cycle_swap_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleSwapRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swap_requests', to='groups.cycle')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swap_requests_sent', to='groups.cyclemembership')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swap_requests_received', to='groups.cyclemembership')),
            ],
            options={
                'indexes': [models.Index(fields=['cycle', 'status'], name='swap_cycle_status_idx'), models.Index(fields=['requester', 'status'], name='swap_requester_status_idx'), models.Index(fields=['target', 'status'], name='swap_target_status_idx')],
            },
        ),
    ]
